### ISSUE TITLE
Please include better usage instructions

### ISSUE THREAD

**Issue by kristianmandrup** [mphasize/sails-generate-ember-blueprints#1]
Just been testing the new SANE 2.0 project generator

https://github.com/artificialio/sane/issues/2#issuecomment-59826965

I end by creating a sails `User` resource. I assume that it will automatically be "hooked up" to be Ember Data compatible using the blueprints? 

It would perhaps be interesting to be able to create a User resource on both ends with YAG (Yet Another Generator)? Wadda you think?

Would be nice with a full example tutorial for how to create such a resource like user, create the Ember Data User and have the full REST going on from Ember View to Sails backend. Thanks ;)

**Comment by mphasize** [comment]
Good point!

**Comment by Globegitter** [comment]
I added some todos and notes in https://github.com/artificialio/sane/issues/9, especially in regards to the generator idea. Feel free to add anything if you have ideas, comments or want to contribute in any way.

**Comment by Globegitter** [comment]
These generators now exist (in the most basic form), the readme here got extended to include a simple example and you can find better tutorials on http://www.100percentjs.com/ as well as http://www.programwitherik.com/sails-js-tutorial-with-ember-js/. So closing this.
