### ISSUE TITLE
Move and improve this feature one sails.js 0.11.x hook

### ISSUE THREAD

**Issue by albertosouza** [mphasize/sails-generate-ember-blueprints#12]
Sais core features are hooks then we can create new features for sails or change the core features  with hooks, and the sails.js 0.11.x has suport to load hooks with npm modules.

Advantages:
1. Suport to upgrades 
2. Easy to install ( npm install sails-hook-emberjs ) and done
3. Has access to all sails.js apis, core features and events

Sails hooks docs: https://github.com/balderdashy/sails/tree/master/lib/hooks

this is the path that will follow but it would be nice move with you guys, if you do not agree, that's fine but it's what i will do.

**Comment by listepo** [comment]
+1

**Comment by mphasize** [comment]
See https://github.com/mdconaway/sails-ember-rest for the latest approach to doing Sails-Ember
