### ISSUE TITLE
Possible bug in advanced blueprints?

### ISSUE THREAD

**Issue by wayne-o** [mphasize/sails-generate-ember-blueprints#14]
I have the following 2 models:

**Comment by mphasize** [comment]
Looks like your comment got swallowed. More Info please. :-)

**Comment by wayne-o** [comment]
Sorry - this shouldn't have sent :)

I thought there was an issue but turned out there wasn't - not sure how it
got submitted

On Thu, Feb 26, 2015 at 3:36 PM, Marcus notifications@github.com wrote:

> Looks like your comment got swallowed. More Info please. :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mphasize/sails-generate-ember-blueprints/issues/14#issuecomment-76199056
> .

## 

_--------------------_

_w://_

_t: 07508 215 459_

_--------------------_
