### ISSUE TITLE
Critical Error: require argument path issue

### ISSUE THREAD

**Issue by Blackening999** [mphasize/sails-generate-ember-blueprints#15]
Please use lowercased path names, cause in insensitive-case systems it will be a blocker.
refer here for  more information: https://github.com/joyent/node/issues/6000

The same issue inside the sails library: https://github.com/balderdashy/sails-hook-dev/issues/3

**Comment by Globegitter** [comment]
Yep sorry that was also here my fault. Will fix as soon as I get to it today. Or if you have time for a pr that would be appreciated as well.
