### ISSUE TITLE
Roadmap 0.2.0

### ISSUE THREAD

**Issue by mphasize** [mphasize/sails-generate-ember-blueprints#18]
### Search for records with existing relationships

probably dependent on [waterline#509](https://github.com/balderdashy/waterline/pull/509)

Quote from discussion on #9:

> I just want to return models who actually have that relationship. So how you can now do http://localhost:1337/api/v1/project?category=bla with a normal attribute, I would love to be able to do http://localhost:1337/api/v1/project?topics=true or something, where-as topics is a relationship attribute in the model
### Enable and honour query parameters to include/exclude relationships and properties

similar to [json-api endpoints sideloading](https://github.com/endpoints/ember-data-endpoints#sideloading)  
maybe dependent on [waterline#855](https://github.com/balderdashy/waterline/issues/855)

Quote from #9 discussion: 

> Also it would be cool to be able to turn sideloading off that way: I am trying here to really optimize the data I am sending to the client, because I am sending a lot of data already, so all that I can reduce really is a win and I actually don't need sideloading for a certain request. 
> 
> And imo even more important would be something like ?select[]=fieldname1&select[]=fieldname2 to further optimize the json size.
### JSON API compliance

As Ember Data moves close to full JSON API compliance and since projects like [Ember Data Endpoints](https://github.com/endpoints/ember-data-endpoints) exist, it would be great to release a set of blueprints that is 100% JSON API compatible.
### Ensure that Websockets are working fine alongside the blueprints

After a quick feedback from @huafu at the end of #13, we believe that the socket connections should work just fine alongside the blueprints, if you're using for instance the socket adapter from [ember-data-sails](https://github.com/huafu/ember-data-sails) for some models you want to fetch over sockets, and the standard REST adapter for the models you want to fetch over HTTP. However, looks like nobody tried it yet, so let's make sure that it works.

**Comment by huafu** [comment]
@mphasize, about the socket, I need to fix some issue which is actually going on with the socket.io/ember mixin somewhere... So as well as I'll be doing this, I am going to actually test using your blueprints in conjonction with my socket adapter for some other models ;-)

Once done and working I am going to publish a release and try to not forget to give you an update here hehe.

**Comment by mphasize** [comment]
@huafu That would be awesome. I appreciate it!

**Comment by mgenev** [comment]
Should I talk about the roadmap here or make separate issues? I have some comments on "Enable and honour query parameters to include/exclude relationships and properties" and it also relates to my plans for addition of geo query support

**Comment by mphasize** [comment]
Feel free to create separate issues, I will try my best to link them back where they belong.

**Comment by huafu** [comment]
@mphasize voila `0.0.13` of my [ember-data-sails](http://huafu.github.io/#/ember?name=ember-data-sails) is now out and I've fixed everything which wasn't working. There was a weird bug with sails socket wrapper generating errors on some unrelated stuff, which was fixed if you disabled ember prototype extensions, so I had to do a hack and wait for the `_raw` socket object, but voila, should be working fine alongside your blueprints. One requirement tho is to put `pluralize` to `true` in the blueprints configuration, as in previous version.

**Comment by IanVS** [comment]
@mphasize Now that JSON API has been tagged at 1.0, what do you think it would take to reach 100% JSON API compliance?  There is a new ember-cli addon called [ember-jsonapi-resources](https://github.com/pixelhandler/ember-jsonapi-resources) that looks pretty fantastic.  Would be great if there were a way to use it with a sails.js backend.

**Comment by mphasize** [comment]
@IanVS I've seen the ember-json-api effort and I'm generally in favor of building a complete JSON-API compliant output for Sails. However, looking at Ember Data it looks like the special REST flavor will stick around for a while and for the next couple of months I will focus my efforts here on finishing the blueprints for Ember Data 1.0. That said, I'm totally open to PRs for this project (and we have the infrastructure for that with templates and blueprint flavors), a fork of this project or another effort to create a JSON-API for Sails.

And to answer your question: I think the effort to make these blueprints JSON API compliant would be reasonable. The 1.0 spec differs slightly in style, but the concepts are essentially the same. So the problems we've already solved can be easily adapted.

**Comment by IanVS** [comment]
So, it seems that Ember Data has embraced JSON-API for their default REST adapter and serializer, and is using JSON-API for all of their internal structures as well.  There was a talk at Wicked Good Ember about this: https://youtu.be/xlplXK6SBao?list=PLE7tQUdRKcyaG1xOBeXbz0dlh7LZkFdyH

Due to these changes, do you think you'll shift focus from the legacy REST flavor to the new JSON-API?  I can try to help out, but I'm pretty unfamiliar with the specs, to be honest.

**Comment by mphasize** [comment]
@IanVS Yes, the plan is indeed to shift to JSON API. The specs are pretty well documented here http://jsonapi.org/ and any help would be greatly appreciated. If you start a PR I can definitely help out. Eventually I'll also get around to do it myself, but the next couple of weeks look pretty busy.

**Comment by IanVS** [comment]
I wonder if it wouldn't make more sense to make a separate `sails-generate-jsonapi-blueprints` project? One of the nice things about JSON-API is that it is standardized and not only for Ember.  I hope it sees widespread adoption across various frameworks and APIs.

Would you be opposed to me taking a stab at creating such a project, based on the way you have this one set up?  We could always pull it back into this project as well, but I think it would be good to have something specific for JSON-API.

**Comment by mphasize** [comment]
Not at all, a proper naming can only benefit the purpose of the project. It should also be possible to implement the new API as a sails-hook instead of blueprints.

**Comment by IanVS** [comment]
I've released an initial version of [sails-hook-jsonapi](https://github.com/IanVS/sails-hook-jsonapi).
