### ISSUE TITLE
following link model name is all lowercase

### ISSUE THREAD

**Issue by wayne-o** [mphasize/sails-generate-ember-blueprints#21]
Not sure the title explains it very well!!

Here is an example:

http://api.test.sonatribe.com/users/5508636667da060300c13012/listingEvents

note the model name is all lowercase

where as if you go here: http://api.test.sonatribe.com/listingEvents/55085e9967da060300c12881

it is now camelcase.

here is my model for user:

```
module.exports = {

  attributes: require('waterlock').models.user.attributes({

    email: 'string',
    username: 'string',
    images: {
        collection: 'image',
        via: 'user'
    },
    avatarImage: {
      model: 'image'
    },

    listingEvents: {
      collection: 'listingEvent',
      via: 'users'
    }

  }),

  beforeCreate: require('waterlock').models.user.beforeCreate,
  beforeUpdate: require('waterlock').models.user.beforeUpdate
};
```

and listingEvent:

```
/**
* ListingEvent.js
*
* @description :: TODO: You might write a short summary of how this model works and what it represents here.
* @docs        :: http://sailsjs.org/#!documentation/models
*/

module.exports = {
//  identity: 'listing_event',
  tableName: 'listingEvent',
  attributes: {
    name: { type: 'string' },
    start: { type: 'date' },
    end: { type: 'date' },
    eventInstanceSlug: { type: 'string' },
    location: {
      model:'location'
    },
    artists: {
      collection: 'artist',
      via: 'listingEvents'
    },
    users: {
        collection: 'user',
        via: 'listingEvents'
    }
  }
};
```

This causes ember to blow out with:

```
WARNING: Encountered "listingevents" in payload, but no model was found for model name "listingevent" (resolved model name using sonatribe-ui@serializer:-rest:.typeForRoot("listingevents"))
ember.debug.js:28602 Error: Assertion Failed: The response from a findHasMany must be an Array, not undefined
    at new Error (native)
```

**Comment by wayne-o** [comment]
could this be related to the commented out code here: https://github.com/mphasize/sails-generate-ember-blueprints/blob/master/templates/advanced/api/services/Ember.js#L44

**Comment by wayne-o** [comment]
I doubt this is a fix that will work but changing this line:

https://github.com/mphasize/sails-generate-ember-blueprints/blob/master/templates/advanced/api/blueprints/populate.js#L88

to this:

`documentIdentifier = association.alias;`

fixes it for me

**Comment by mphasize** [comment]
@wayne-o well spotted! I'll take a look on friday and see if I can fix it.

**Comment by wayne-o** [comment]
Another one for you :)

here is an object referenced by it's ID:

http://api.test.sonatribe.com/listingevents/550a98aede655a03004520e1

Here is the same object referenced by it's association:

http://api.test.sonatribe.com/artists/550a98afde655a03004520e3/listingEvents

Notice the hasOne location link isn't present when being called through the association

**Comment by mphasize** [comment]
@wayne-o In the last example you sent me, all the data seems to be there. (I cannot see the missing link.) The difference I see however, is that the result is returned as an object and not in an array. That's something I should fix.

**Comment by wayne-o** [comment]
Apologies the api has been updated since with my code changes. I should have screen grabbed the output

**Comment by mphasize** [comment]
@wayne-o I fixed the publish blueprint to use the correct model ID / document identifier.

I think you can name the `association.alias` to something different than the model name, so we wouldn't want to use that directly. Cheers!

**Comment by wayne-o** [comment]
nice one - will test this out in the am

On Sun, Mar 22, 2015 at 4:13 PM, Marcus notifications@github.com wrote:

> @wayne-o https://github.com/wayne-o I fixed the publish blueprint to
> use the correct model ID / document identifier.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mphasize/sails-generate-ember-blueprints/issues/21#issuecomment-84644785
> .

## 

_--------------------_

_w://_

_t: 07508 215 459_

_--------------------_
