### ISSUE TITLE
Exclude particular associations

### ISSUE THREAD

**Issue by timohofmeijer** [mphasize/sails-generate-ember-blueprints#35]
Passport is part of my setup. I used to delete the `passports` property in the `toJSON` method, but with the `advanced` blueprints it is part of the response. Do you perhaps have a way of preventing this? `includeIn: false`? :no_mouth:

**Comment by mphasize** [comment]
@timohofmeijer The `includeIn` parameter is only evaluated for associations/relationships, so deleting your property inside the `toJSON` method should still be the right way to do it.

I'm using this in one of my applications and it works well with the advanced API:

``` javascript
//Override toJSON method to remove password from API
toJSON: function () {
    var obj = this.toObject();
    delete obj.password;
    return obj;
}
```

**Comment by timohofmeijer** [comment]
Odd.. thats exactly what I'm doing. It is a hasmany association with multiple passports, could that make a difference?. Passport are listed in the response when querying a single user as well as when querying multiple.

**Comment by mphasize** [comment]
Yes, that would make a difference. As far as I know you don't have access to the associations inside toJSON (there are a couple of issues and pr's around some weird behavior there). If your passports come in the form of an association, an `includeIn: false` as you suggested earlier makes a lot more sense to me now. Would you be interested in creating a PR for that?

**Comment by blia** [comment]
At now `includeIn: { list: false, detail: false }` works fine.
