### ISSUE TITLE
sideloaded models are not capitalized. (or, non-sideloaded models strangely capitalized)

### ISSUE THREAD

**Issue by aars** [mphasize/sails-generate-ember-blueprints#36]
Sideloaded models are not capitalized in the returned json, for example:

```
// GET /testmodels
{
  "testModels": [
    {
      "relations": [
        10
      ],
      "foo": "bar",
      "createdAt": "2015-05-11T14:26:07.238Z",
      "updatedAt": "2015-05-11T14:26:07.238Z",
      "id": 18
    }
  ],
  "testrelations": [
    {
      "someFoo": "someBar",
      "model": 18,
      "createdAt": "2015-05-11T14:26:07.243Z",
      "updatedAt": "2015-05-11T14:26:07.244Z",
      "id": 10
    }
  ],
  "meta": {
    "total": 1
  }
}
```

And the other way around:

```
// GET /testrelations
{
  "testRelations": [
    {
      "model": 18,
      "someFoo": "someBar",
      "createdAt": "2015-05-11T14:26:07.243Z",
      "updatedAt": "2015-05-11T14:26:07.244Z",
      "id": 10
    }
  ],
  "testmodels": [
    {
      "foo": "bar",
      "createdAt": "2015-05-11T14:26:07.238Z",
      "updatedAt": "2015-05-11T14:26:07.238Z",
      "id": 18,
      "links": {
        "relations": "/testmodels/18/relations"
      }
    }
  ],
  "meta": {
    "total": 1
  }
}
```

Here is the test setup I built to confirm this behaviour: https://github.com/aars/sails-generate-ember-blueprints-capitalisation

Of course now the issue is, Ember doesn't understand one of these since the ember models are either capitalized or not. (in this case the models name would be `testmodel` or `testModel` or 'TestModel`, neither of which matches all the cases).

Am I doing something wrong? Should I remove all capitalization from my serverside models?

I'm guessing I can resolve this by tweaking the `Ember.buildResponse` method, but I'm wondering if this is desired behaviour, and if so, how to handle it.

Cheers.

**Comment by aars** [comment]
Ooh! Is this the fix? https://github.com/mphasize/sails-generate-ember-blueprints/commit/507ed8c4bb6566526e5b25457a3f5df02f611f47

**Comment by mphasize** [comment]
@aars The desired outcome would definitely be capitalized models. Is the fix still missing somewhere? Which version of the blueprints are you using? (version number and basic or advanced?)

**Comment by aars** [comment]
Grrr.. did not `--save` on `npm install` so it was missing from my test repo. I'm using 0.0.7 with advanced blueprints.

```
npm list sails-generate-ember-blueprints                        
test@0.0.0 /Users/aaronh/src/sails-ember-capitalisation-stuff/test
└── sails-generate-ember-blueprints@0.0.7
```

**Comment by aars** [comment]
Odd. The changes in https://github.com/mphasize/sails-generate-ember-blueprints/commit/507ed8c4bb6566526e5b25457a3f5df02f611f47 are in my local 0.0.7 install. (the test repository)

**Comment by aars** [comment]
I'm getting the feeling the issue is in sails itself.. Associations are already lowercased here: https://github.com/balderdashy/sails/blob/master/lib/hooks/orm/build-orm.js#L87

**Comment by aars** [comment]
Ok, I'm pretty sure now that this is a Waterline issue and can only be resolved by not using camelCased model names. You can see here that Waterline intentionally undercases the model names in associations: https://github.com/balderdashy/waterline-schema/issues/4

**Comment by aars** [comment]
Mmm.. even though I still think the underlying issue is in waterline. I think it can be fixed in the Ember service here. Maybe even should be fixed there. It would mean to using `sails.models[lowercasedmodelname].globalId` when formatting the json output. That would also mean that the current output would change, since the 'original' model name, as defined by the filename, would be presented. So in this test setup it would return `TestModels` and `TestRelations` as opposed to 'testModels`and`testRelations`. Which I think is very odd behaviour, those are simply _not_ the names of the models.

**Comment by mphasize** [comment]
@Globegitter Any ideas on this one? I won't be able to take a deeper look until the weekend.

**Comment by aars** [comment]
https://github.com/mphasize/sails-generate-ember-blueprints/pull/37
