### ISSUE TITLE
Specify association depth

### ISSUE THREAD

**Issue by alexjp** [mphasize/sails-generate-ember-blueprints#4]
Hi,

Could if be possible to allow the depth of associations ( or childs of childs ) to sideload, or specify the models to sideload?

so, something like a -> b ,  b -> c

and json send a, b and c?

**Comment by mphasize** [comment]
Well, while it's possible to build something like this, it should actually come from Sails / Waterline and would then be dependent on something like nested associations! See https://github.com/balderdashy/waterline/issues/308

**Comment by alexjp** [comment]
Closing because should be on waterline, thanks mphasize

**Comment by mphasize** [comment]
Thanks for cleaning the house. :-)
