### ISSUE TITLE
QUESTION: Best practices for integrating these blueprints with custom routes

### ISSUE THREAD

**Issue by Andrew-Max** [mphasize/sails-generate-ember-blueprints#41]
Recently started using this library to get our sails backend to talk to the ember rest adapter. It's an awesome library so thanks!

I have one major question regarding how to implement this though:

As far as I know (and I'm very new to sails) custom defined routes do not ever interact with blueprints. After getting the blueprints running, our custom controller actions still return json in the old format.

Obviously we could construct the response object in the correct format inside of each action but I don't want to replicate that effort in every action.

Right now my work around is to require the actionUtil library and use its utilities to run emberizeJSON with the properly parsed data eg:

```
///userController.js
  create: function (req, res) {
  User.create (req.body)
 .then(function(user)
      var model = emberUtils.parseModel( req );
      var userJson =  emberizeJSON(model, user, null, false)
      return res.json(userJson);
})
}
```

(bear in mind this example is really contrived. I would do it slightly differently in reality)

Has anyone come up with a better way to do this? Is there a way to get the blueprints to interact with custom controller actions. Has anyone tried to implement a serializer object based off of the functions in the actionUtil library?

Thanks again for the help and for the awesome library!

**Comment by mphasize** [comment]
Hi @Andrew-Max, with what we have at the moment, this is probably the best you can get. If you have a similar controller action in different controllers, you could create another blueprint (e.g. I'm using a `publish` blueprint in my app), but that's about it.
When we manage to turn this project from a generator into a `sails-hook`, things should get easier, but don't expect that to happen very soon. Cheers!

**Comment by Andrew-Max** [comment]
Would there be any interest if I were to submit a pull request that created a serializer object inside of a service that could deal with serialization in custom actions in a clean way or does that fall outside of what you see as the scope of this project?

I'm thinking something like rails' active model serializers. Coming from the rails world, I really miss this functionality.

**Comment by mphasize** [comment]
@Andrew-Max I'm not very familiar with Rails Serializers, but if I understand correctly what you are suggesting, it should still be within the scope of this project. I'd be happy to support custom actions in an easy and clean manner!

**Comment by Andrew-Max** [comment]
Basic idea, is that  you would have a  service called UserSerializer and would be able to do something like: 

User.findOne(1)
.then(function(user){
return res.json(UserSerializer.serialize(user, argsArray)
}) 

Where the user serializer would contain instructions for how to serialize a user object and could possibly take args which could allow you to specify different serialization schemes.

You could possibly have a base serializer which others inherited from which could make things default  to being restAdapter compliant

I'm going to close this and start working on this sometime soon when I get a chance
