### ISSUE TITLE
Contributor access to project

### ISSUE THREAD

**Issue by Globegitter** [mphasize/sails-generate-ember-blueprints#5]
Hey @mphasize thanks for creating this project. I was wondering if I could contributor access to this repository just so I could make changes/enhancement/merge PRs when needed?

I am not planning to do anything in the short-term, but would be great for when I have some more time in the following weeks when I might have a burst of time just so I can move on things quickly.

I am not planning to change anything hugely - the goal really just is to get as close as possible to http://jsonapi.org/ standard with embedded records support, good performance, etc.

Let me know :)

**Comment by mphasize** [comment]
If you want to get busy, I don't want to hold you. :-) Let's try it out.
I would appreciate it, if you could use feature-branches and PR's in the repo to at least document the changes you're making and I might also be able to do some reviews quickly.

**Comment by mphasize** [comment]
What should be on the immediate roadmap?

**Comment by Globegitter** [comment]
Yes of course - I will use my power wisely ;) Once I make PRs I will leave them open for at least a day or two. Thank you!

A few things came up multiple times already within Sane. | don't know of the top of my head and I know that within the next few weeks I am busy with other things, but I can see it moving up slowly the priority list.
I will of course let you know beforehand once it moved up the list. And if you have any interest in joining [Gitter](https://github.com/mikermcneil/machinepack-npm) I could also send you messages there :)

**Comment by mphasize** [comment]
Sounds good to me! :)
