### ISSUE TITLE
Library Modernization

### ISSUE THREAD

**Issue by mdconaway** [mphasize/sails-generate-ember-blueprints#55]
Mphasize,

I can see you have moved on to other things, but my group heavily uses this library and has started to refactor it a bit with the goal of making it usable as sails moves into version 1.0+.

I just posted it on GitHub and NPM:
https://github.com/mdconaway/sails-ember-rest
https://www.npmjs.com/package/sails-ember-rest

Let me know if there is anything else I can do to cite your library as being the original source, and if you have any recommendations on implementing changes going forward.

Thanks for knocking out all the heavy lifting!

**Comment by mphasize** [comment]
@mdconaway Excellent news and thanks for the attribution. I'm happy to link to the effort from this repo and help to move some users over.

**Comment by mdconaway** [comment]
Yeah, that sounds great! I'd like to keep the momentum for this project alive, it has made building a CRUD server a trivial task and reduced my team's iteration cycle time drastically.

**Comment by mdconaway** [comment]
Hey mphasize, I just made a pull request to add a link in the readme.

[https://github.com/mphasize/sails-generate-ember-blueprints/pull/56](https://github.com/mphasize/sails-generate-ember-blueprints/pull/56)

Thanks!

**Comment by mphasize** [comment]
Already merged :-)
